FROM node:20-alpine AS build
WORKDIR /app

ARG VITE_API_URL
ARG VITE_BASE_URL
ARG VITE_SUPPORT_URL

ENV VITE_BASE_URL=$VITE_BASE_URL
ENV VITE_API_URL=$VITE_API_URL
ENV VITE_SUPPORT_URL=$VITE_SUPPORT_URL


COPY package*.json ./
RUN npm install
COPY . ./
CMD ["npm", "run", "build"]